spring.application.name=app

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://ep-proud-sound-agciboj9-pooler.c-2.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_lRZz7iM6XwBS&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lRZz7iM6XwBS

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# H2 Web Console (disabled for PostgreSQL)
spring.h2.console.enabled=false

#Cloudinary connection
cloudinary.cloud_name=dk6szwtyh
cloudinary.api_key=118151498237972
cloudinary.api_secret=7E-5YHwiYrK-K8dA0Yw0vnuyKfM


